name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and build frontend (on GitHub Actions server)
      - name: Setup Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Change this to your Node.js version

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Deploy to Droplet via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Navigate to backend folder, pull latest changes, install dependencies, and restart PM2
            cd /app/aztec
            git pull origin main
            cd /app/aztec/backend
            npm install
            pm2 restart all  # Assuming PM2 is already managing your backend process

            # Copy frontend build to /app/aztec/frontend/build from build frontend step
            cp -r /github/workspace/frontend/build /app/aztec/frontend/build
