name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Droplet via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          debug: true
          script: |
            echo "Successfully connected to the server"
            ls -la /home/${{ secrets.DROPLET_USER }}
            cd /app/aztec
            git pull origin main
            cd /app/aztec/backend
            npm install
            pm2 restart all
